route:
  receiver: 'containers_notification'
receivers:
- name: 'containers_notification'
  slack_configs:
    - api_url: '[[YOUR SLACK WEB HOOK]]' #TODO
      channel: '#general'
      text: "{{ .CommonAnnotations.summary }}"
      send_resolved: true