route:
  receiver: 'containers_notification'
receivers:
- name: 'containers_notification'
  slack_configs:
    - api_url: 'https://hooks.slack.com/services/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'
      channel: '#general'
      text: "{{ .CommonAnnotations.summary }}"
      send_resolved: true