version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /Users/nishipy/Projects/Prometheus/2_Beginning/prometheus.yaml:/etc/prometheus/prometheus.yml
      - /Users/nishipy/Projects/Prometheus/2_Beginning/rules.yaml:/etc/prometheus/rules.yaml
    ports:
      - 9090:9090
  node-exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs
  alert-manager:
    image: prom/alertmanager
    container_name: alert-manager
    ports:
      - 9093:9093
    volumes:
      - /Users/nishipy/Projects/Prometheus/2_Beginning/alertmanager.yaml:/alertmanager/alertmanager.yml
    command:
      - '--config.file=/alertmanager/alertmanager.yml'
    privileged: true