version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /Local/Path/To/prometheus.yaml:/etc/prometheus/prometheus.yml # TODO
      - /Local/Path/To/rules.yaml:/etc/prometheus/rules.yaml # TODO
    ports:
      - 9090:9090
  node-exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs
  alert-manager:
    image: prom/alertmanager
    container_name: alert-manager
    ports:
      - 9093:9093
    volumes:
      - /Local/Path/To/alertmanager.yaml:/alertmanager/alertmanager.yml
    command:
      - '--config.file=/alertmanager/alertmanager.yml'
    privileged: true