global:
  scrape_interval:     10s
  evaluation_interval: 10s
  external_labels:
      monitor: 'codelab-monitor'
rule_files:
 - rules.yaml
alerting:
  alertmanagers:
  - static_configs:
     - targets: ['10.0.1.7:9093']
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
      - targets: ['10.0.1.7:9100']