global:
  scrape_interval:     10s
  evaluation_interval: 10s
  external_labels:
      monitor: 'codelab-monitor'
rule_files:
 - rules.yaml
alerting:
  alertmanagers:
  - static_configs:
     - targets: ['[[YOUR PRIVATE IP]]:9093'] #TODO
scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['[[YOUR PRIVATE IP]]:9100'] #TODO
  - job_name: 'web'
    static_configs:
      - targets: ['[[YOUR PRIVATE IP]]:8000'] #TODO